version: "3"

services:
  web:
    build: .
    command: gunicorn mysite.wsgi --bind 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - ./mysite:/code
    depends_on:
      - db
    networks:
      - backend
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_HOST: "db"
      DJANGO_WEB_HOST: "web"
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  nginx:
    image: nginx:latest
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./mysite/static:/code/static
    networks:
      - backend
    depends_on:
      - web
    environment:
      DJANGO_WEB_HOST: "web"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
